services:
  gateway:
    build:
      context: ./src
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
    - 8080:8080
    - 5678:5678
    volumes:
    - ./logs:/app/logs
    environment:
      PYTHONUNBUFFERED: '1'
      LOG_FILE: /app/logs/gateway.txt
      SERVER_HOST: gateway
      SERVER_PORT: '5678'
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      OUTPUTS_QUEUE: q3_raw_data
      INPUTS_QUEUE: q3_results
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: '8080'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_LOG_LEVELS: error
      RABBITMQ_DEFAULT_USER: distributed
      RABBITMQ_DEFAULT_PASS: distributed
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  q3_filter_usd_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '1'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_01.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_usd_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '2'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_02.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_usd_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '3'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_03.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_usd_04:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '4'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_04.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_fechas_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 3, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 3, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '1'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_01.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_filter_fechas_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 3, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 3, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '2'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_02.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_filter_fechas_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 3, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 3, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '3'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_03.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_filter_fechas_04:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 3, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 3, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '4'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_04.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_format_shard_01:
    build:
      context: ./src
      dockerfile: workers/format_shard/Dockerfile
    container_name: q3_format_shard_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q3_temprano_1", "q3_tardio_1"]'
      OUTPUT_QUEUES: q3_results
      NODE_PREFIX: q3_format_shard
      ID: '1'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q3_format_shard_01.txt
  q3_format_shard_02:
    build:
      context: ./src
      dockerfile: workers/format_shard/Dockerfile
    container_name: q3_format_shard_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q3_temprano_2", "q3_tardio_2"]'
      OUTPUT_QUEUES: q3_results
      NODE_PREFIX: q3_format_shard
      ID: '2'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q3_format_shard_02.txt
  q3_format_shard_03:
    build:
      context: ./src
      dockerfile: workers/format_shard/Dockerfile
    container_name: q3_format_shard_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q3_temprano_3", "q3_tardio_3"]'
      OUTPUT_QUEUES: q3_results
      NODE_PREFIX: q3_format_shard
      ID: '3'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q3_format_shard_03.txt
