services:
  gateway:
    build:
      context: ./src
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
    - 8080:8080
    - 5678:5678
    volumes:
    - ./logs:/app/logs
    environment:
      PYTHONUNBUFFERED: '1'
      LOG_FILE: /app/logs/gateway.txt
      SERVER_HOST: gateway
      SERVER_PORT: '5678'
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      OUTPUTS_QUEUE: q3_raw_data, q2_raw_data, q4_raw_data, q1_raw_data, q5_raw_data
      INPUTS_QUEUE: q3_results, q2_results, q4_results, q1_results, q5_results
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: '8080'
      BANK_QUEUE: '{"queue_shard_prefix": "q2_raw_banks", "total_workers": 3, "hash_field": "Bank ID"}'
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_LOG_LEVELS: error
      RABBITMQ_DEFAULT_USER: distributed
      RABBITMQ_DEFAULT_PASS: distributed
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  q3_filter_usd_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '1'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_01.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_usd_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '2'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_02.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_usd_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '3'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_03.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_usd_04:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_usd_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_raw_data
      OUTPUT_QUEUES: q3_usd_filtered
      NODE_PREFIX: q3_filter_usd
      ID: '4'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_usd_04.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q3_filter_fechas_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 2, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 2, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '1'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_01.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_filter_fechas_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 2, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 2, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '2'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_02.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_filter_fechas_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 2, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 2, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '3'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_03.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_filter_fechas_04:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q3_filter_fechas_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q3_usd_filtered
      OUTPUT_QUEUES: '[{"type": "conditional", "condition_field": "Timestamp", "cases": [{"operator": "between", "value": "2022/09/01,2022/09/05", "routing": {"queue_shard_prefix": "q3_temprano", "total_workers": 2, "hash_field": "Payment Format"}}, {"operator": "between", "value": "2022/09/06,2022/09/15", "routing": {"queue_shard_prefix": "q3_tardio", "total_workers": 2, "hash_field": "Payment Format"}}]}]'
      NODE_PREFIX: q3_filter_fechas
      ID: '4'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q3_filter_fechas_04.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01,2022/09/15
      FILTER_OPERATOR: between
  q3_format_shard_01:
    build:
      context: ./src
      dockerfile: workers/format_shard/Dockerfile
    container_name: q3_format_shard_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q3_temprano_1", "q3_tardio_1"]'
      OUTPUT_QUEUES: q3_results
      NODE_PREFIX: q3_format_shard
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q3_format_shard_01.txt
  q3_format_shard_02:
    build:
      context: ./src
      dockerfile: workers/format_shard/Dockerfile
    container_name: q3_format_shard_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q3_temprano_2", "q3_tardio_2"]'
      OUTPUT_QUEUES: q3_results
      NODE_PREFIX: q3_format_shard
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q3_format_shard_02.txt
  q2_filter_usd_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q2_filter_usd_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_raw_data
      OUTPUT_QUEUES: '["q2_pre_projection"]'
      NODE_PREFIX: q2_filter_usd
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q2_filter_usd_01.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q2_filter_usd_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q2_filter_usd_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_raw_data
      OUTPUT_QUEUES: '["q2_pre_projection"]'
      NODE_PREFIX: q2_filter_usd
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q2_filter_usd_02.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q2_bank_projection_01:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_bank_projection_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_raw_banks_1
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_banks", "total_workers": 6, "hash_field": "Bank ID"}]'
      NODE_PREFIX: q2_bank_projection
      ID: '1'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q2_bank_projection_01.txt
      CAMPOS: Bank ID,Bank Name,Account Number
      INT_FIELDS: ''
  q2_bank_projection_02:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_bank_projection_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_raw_banks_2
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_banks", "total_workers": 6, "hash_field": "Bank ID"}]'
      NODE_PREFIX: q2_bank_projection
      ID: '2'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q2_bank_projection_02.txt
      CAMPOS: Bank ID,Bank Name,Account Number
      INT_FIELDS: ''
  q2_bank_projection_03:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_bank_projection_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_raw_banks_3
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_banks", "total_workers": 6, "hash_field": "Bank ID"}]'
      NODE_PREFIX: q2_bank_projection
      ID: '3'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q2_bank_projection_03.txt
      CAMPOS: Bank ID,Bank Name,Account Number
      INT_FIELDS: ''
  q2_projection_01:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_projection_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_pre_projection
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_transactions", "total_workers": 6, "hash_field": "From Bank"}]'
      NODE_PREFIX: q2_projection
      ID: '1'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_projection_01.txt
      CAMPOS: From Bank,Account,Payment Currency,Receiving Currency,Amount Received,Amount Paid
      INT_FIELDS: From Bank
  q2_projection_02:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_projection_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_pre_projection
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_transactions", "total_workers": 6, "hash_field": "From Bank"}]'
      NODE_PREFIX: q2_projection
      ID: '2'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_projection_02.txt
      CAMPOS: From Bank,Account,Payment Currency,Receiving Currency,Amount Received,Amount Paid
      INT_FIELDS: From Bank
  q2_projection_03:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_projection_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_pre_projection
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_transactions", "total_workers": 6, "hash_field": "From Bank"}]'
      NODE_PREFIX: q2_projection
      ID: '3'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_projection_03.txt
      CAMPOS: From Bank,Account,Payment Currency,Receiving Currency,Amount Received,Amount Paid
      INT_FIELDS: From Bank
  q2_projection_04:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_projection_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_pre_projection
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_transactions", "total_workers": 6, "hash_field": "From Bank"}]'
      NODE_PREFIX: q2_projection
      ID: '4'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_projection_04.txt
      CAMPOS: From Bank,Account,Payment Currency,Receiving Currency,Amount Received,Amount Paid
      INT_FIELDS: From Bank
  q2_projection_05:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_projection_05
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_pre_projection
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_transactions", "total_workers": 6, "hash_field": "From Bank"}]'
      NODE_PREFIX: q2_projection
      ID: '5'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_projection_05.txt
      CAMPOS: From Bank,Account,Payment Currency,Receiving Currency,Amount Received,Amount Paid
      INT_FIELDS: From Bank
  q2_projection_06:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q2_projection_06
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q2_pre_projection
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q2_shard_transactions", "total_workers": 6, "hash_field": "From Bank"}]'
      NODE_PREFIX: q2_projection
      ID: '6'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_projection_06.txt
      CAMPOS: From Bank,Account,Payment Currency,Receiving Currency,Amount Received,Amount Paid
      INT_FIELDS: From Bank
  q2_agregador_shard_01:
    build:
      context: ./src
      dockerfile: workers/bank_shard/Dockerfile
    container_name: q2_agregador_shard_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q2_shard_transactions_1", "q2_shard_banks_1"]'
      OUTPUT_QUEUES: q2_results
      NODE_PREFIX: q2_agregador_shard
      ID: '1'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_agregador_shard_01.txt
  q2_agregador_shard_02:
    build:
      context: ./src
      dockerfile: workers/bank_shard/Dockerfile
    container_name: q2_agregador_shard_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q2_shard_transactions_2", "q2_shard_banks_2"]'
      OUTPUT_QUEUES: q2_results
      NODE_PREFIX: q2_agregador_shard
      ID: '2'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_agregador_shard_02.txt
  q2_agregador_shard_03:
    build:
      context: ./src
      dockerfile: workers/bank_shard/Dockerfile
    container_name: q2_agregador_shard_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q2_shard_transactions_3", "q2_shard_banks_3"]'
      OUTPUT_QUEUES: q2_results
      NODE_PREFIX: q2_agregador_shard
      ID: '3'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_agregador_shard_03.txt
  q2_agregador_shard_04:
    build:
      context: ./src
      dockerfile: workers/bank_shard/Dockerfile
    container_name: q2_agregador_shard_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q2_shard_transactions_4", "q2_shard_banks_4"]'
      OUTPUT_QUEUES: q2_results
      NODE_PREFIX: q2_agregador_shard
      ID: '4'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_agregador_shard_04.txt
  q2_agregador_shard_05:
    build:
      context: ./src
      dockerfile: workers/bank_shard/Dockerfile
    container_name: q2_agregador_shard_05
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q2_shard_transactions_5", "q2_shard_banks_5"]'
      OUTPUT_QUEUES: q2_results
      NODE_PREFIX: q2_agregador_shard
      ID: '5'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_agregador_shard_05.txt
  q2_agregador_shard_06:
    build:
      context: ./src
      dockerfile: workers/bank_shard/Dockerfile
    container_name: q2_agregador_shard_06
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q2_shard_transactions_6", "q2_shard_banks_6"]'
      OUTPUT_QUEUES: q2_results
      NODE_PREFIX: q2_agregador_shard
      ID: '6'
      TOTAL_WORKERS: '6'
      LOG_FILE: /app/logs/q2_agregador_shard_06.txt
  q4_filter_usd_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q4_filter_usd_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_raw_data
      OUTPUT_QUEUES: '["q4_pre_projection"]'
      NODE_PREFIX: q4_filter_usd
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q4_filter_usd_01.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q4_filter_usd_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q4_filter_usd_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_raw_data
      OUTPUT_QUEUES: '["q4_pre_projection"]'
      NODE_PREFIX: q4_filter_usd
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q4_filter_usd_02.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q4_projection_01:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q4_projection_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_pre_projection
      OUTPUT_QUEUES: q4_projected
      NODE_PREFIX: q4_projection
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q4_projection_01.txt
      CAMPOS: From Bank,Account,To Bank,Account.1,Timestamp
      INT_FIELDS: ''
  q4_projection_02:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q4_projection_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_pre_projection
      OUTPUT_QUEUES: q4_projected
      NODE_PREFIX: q4_projection
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q4_projection_02.txt
      CAMPOS: From Bank,Account,To Bank,Account.1,Timestamp
      INT_FIELDS: ''
  q4_filter_period_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q4_filter_period_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_projected
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_to_sumador", "total_workers": 3, "hash_fields": ["From Bank", "Account"]}, {"queue_shard_prefix": "q4_to_joiner", "total_workers": 3, "hash_fields": ["From Bank", "Account"]}]'
      NODE_PREFIX: q4_filter_period
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q4_filter_period_01.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01, 2022/09/05
      FILTER_OPERATOR: between
  q4_filter_period_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q4_filter_period_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_projected
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_to_sumador", "total_workers": 3, "hash_fields": ["From Bank", "Account"]}, {"queue_shard_prefix": "q4_to_joiner", "total_workers": 3, "hash_fields": ["From Bank", "Account"]}]'
      NODE_PREFIX: q4_filter_period
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q4_filter_period_02.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01, 2022/09/05
      FILTER_OPERATOR: between
  q4_sumador_01:
    build:
      context: ./src
      dockerfile: workers/group_distinct_counter/Dockerfile
    container_name: q4_sumador_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_to_sumador_1
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_scatter_edges", "total_workers": 3, "hash_fields": ["to_bank", "to_account"]}]'
      NODE_PREFIX: q4_sumador
      ID: '1'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_sumador_01.txt
      GROUP_FIELDS: From Bank,Account
      GROUP_OUTPUT_FIELDS: from_bank,from_account
      VALUE_FIELDS: To Bank,Account.1
      VALUE_OUTPUT_FIELDS: to_bank,to_account
      EXPECTED_COUNT: '5'
      EMIT_MODE: explode
  q4_sumador_02:
    build:
      context: ./src
      dockerfile: workers/group_distinct_counter/Dockerfile
    container_name: q4_sumador_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_to_sumador_2
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_scatter_edges", "total_workers": 3, "hash_fields": ["to_bank", "to_account"]}]'
      NODE_PREFIX: q4_sumador
      ID: '2'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_sumador_02.txt
      GROUP_FIELDS: From Bank,Account
      GROUP_OUTPUT_FIELDS: from_bank,from_account
      VALUE_FIELDS: To Bank,Account.1
      VALUE_OUTPUT_FIELDS: to_bank,to_account
      EXPECTED_COUNT: '5'
      EMIT_MODE: explode
  q4_sumador_03:
    build:
      context: ./src
      dockerfile: workers/group_distinct_counter/Dockerfile
    container_name: q4_sumador_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_to_sumador_3
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_scatter_edges", "total_workers": 3, "hash_fields": ["to_bank", "to_account"]}]'
      NODE_PREFIX: q4_sumador
      ID: '3'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_sumador_03.txt
      GROUP_FIELDS: From Bank,Account
      GROUP_OUTPUT_FIELDS: from_bank,from_account
      VALUE_FIELDS: To Bank,Account.1
      VALUE_OUTPUT_FIELDS: to_bank,to_account
      EXPECTED_COUNT: '5'
      EMIT_MODE: explode
  q4_joiner_01:
    build:
      context: ./src
      dockerfile: workers/joiner_q4/Dockerfile
    container_name: q4_joiner_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q4_scatter_edges_1", "q4_to_joiner_1"]'
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_paths", "total_workers": 3, "hash_fields": ["a_bank", "a_account", "c_bank", "c_account"]}]'
      NODE_PREFIX: q4_joiner
      ID: '1'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_joiner_01.txt
  q4_joiner_02:
    build:
      context: ./src
      dockerfile: workers/joiner_q4/Dockerfile
    container_name: q4_joiner_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q4_scatter_edges_2", "q4_to_joiner_2"]'
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_paths", "total_workers": 3, "hash_fields": ["a_bank", "a_account", "c_bank", "c_account"]}]'
      NODE_PREFIX: q4_joiner
      ID: '2'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_joiner_02.txt
  q4_joiner_03:
    build:
      context: ./src
      dockerfile: workers/joiner_q4/Dockerfile
    container_name: q4_joiner_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: '["q4_scatter_edges_3", "q4_to_joiner_3"]'
      OUTPUT_QUEUES: '[{"queue_shard_prefix": "q4_paths", "total_workers": 3, "hash_fields": ["a_bank", "a_account", "c_bank", "c_account"]}]'
      NODE_PREFIX: q4_joiner
      ID: '3'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_joiner_03.txt
  q4_contador_01:
    build:
      context: ./src
      dockerfile: workers/group_distinct_counter/Dockerfile
    container_name: q4_contador_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_paths_1
      OUTPUT_QUEUES: q4_results
      NODE_PREFIX: q4_contador
      ID: '1'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_contador_01.txt
      GROUP_FIELDS: a_bank,a_account,c_bank,c_account
      GROUP_OUTPUT_FIELDS: From Bank,From Account,To Bank,To Account
      VALUE_FIELDS: b_bank,b_account
      EXPECTED_COUNT: '5'
      EMIT_MODE: aggregate
      COUNT_OUTPUT_FIELD: Amount Transactions
  q4_contador_02:
    build:
      context: ./src
      dockerfile: workers/group_distinct_counter/Dockerfile
    container_name: q4_contador_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_paths_2
      OUTPUT_QUEUES: q4_results
      NODE_PREFIX: q4_contador
      ID: '2'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_contador_02.txt
      GROUP_FIELDS: a_bank,a_account,c_bank,c_account
      GROUP_OUTPUT_FIELDS: From Bank,From Account,To Bank,To Account
      VALUE_FIELDS: b_bank,b_account
      EXPECTED_COUNT: '5'
      EMIT_MODE: aggregate
      COUNT_OUTPUT_FIELD: Amount Transactions
  q4_contador_03:
    build:
      context: ./src
      dockerfile: workers/group_distinct_counter/Dockerfile
    container_name: q4_contador_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q4_paths_3
      OUTPUT_QUEUES: q4_results
      NODE_PREFIX: q4_contador
      ID: '3'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q4_contador_03.txt
      GROUP_FIELDS: a_bank,a_account,c_bank,c_account
      GROUP_OUTPUT_FIELDS: From Bank,From Account,To Bank,To Account
      VALUE_FIELDS: b_bank,b_account
      EXPECTED_COUNT: '5'
      EMIT_MODE: aggregate
      COUNT_OUTPUT_FIELD: Amount Transactions
  01_filter_usd_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: 01_filter_usd_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q1_raw_data
      OUTPUT_QUEUES: '["q1_pre_projection"]'
      NODE_PREFIX: 01_filter_usd
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/01_filter_usd_01.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  01_filter_usd_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: 01_filter_usd_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q1_raw_data
      OUTPUT_QUEUES: '["q1_pre_projection"]'
      NODE_PREFIX: 01_filter_usd
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/01_filter_usd_02.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq
  q1_projection_01:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q1_projection_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q1_pre_projection
      OUTPUT_QUEUES: q1_usd_to_minor_50
      NODE_PREFIX: q1_projection
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q1_projection_01.txt
      CAMPOS: From Bank,Account,To Bank,Account.1,Amount Paid
      INT_FIELDS: From Bank
  q1_projection_02:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q1_projection_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q1_pre_projection
      OUTPUT_QUEUES: q1_usd_to_minor_50
      NODE_PREFIX: q1_projection
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q1_projection_02.txt
      CAMPOS: From Bank,Account,To Bank,Account.1,Amount Paid
      INT_FIELDS: From Bank
  q1_minor_than_50_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q1_minor_than_50_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q1_usd_to_minor_50
      OUTPUT_QUEUES: q1_results
      NODE_PREFIX: q1_minor_than_50
      ID: '1'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q1_minor_than_50_01.txt
      FILTER_FIELD: Amount Paid
      FILTER_VALUE: '50'
      FILTER_OPERATOR: lt
  q1_minor_than_50_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q1_minor_than_50_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q1_usd_to_minor_50
      OUTPUT_QUEUES: q1_results
      NODE_PREFIX: q1_minor_than_50
      ID: '2'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q1_minor_than_50_02.txt
      FILTER_FIELD: Amount Paid
      FILTER_VALUE: '50'
      FILTER_OPERATOR: lt
  q1_minor_than_50_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q1_minor_than_50_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q1_usd_to_minor_50
      OUTPUT_QUEUES: q1_results
      NODE_PREFIX: q1_minor_than_50
      ID: '3'
      TOTAL_WORKERS: '3'
      LOG_FILE: /app/logs/q1_minor_than_50_03.txt
      FILTER_FIELD: Amount Paid
      FILTER_VALUE: '50'
      FILTER_OPERATOR: lt
  q5_projection_01:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q5_projection_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_raw_data
      OUTPUT_QUEUES: q5_projected_data
      NODE_PREFIX: q5_projection
      ID: '1'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_projection_01.txt
      CAMPOS: Timestamp,Payment Currency,Receiving Currency,Payment Format,Amount Received
  q5_projection_02:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q5_projection_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_raw_data
      OUTPUT_QUEUES: q5_projected_data
      NODE_PREFIX: q5_projection
      ID: '2'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_projection_02.txt
      CAMPOS: Timestamp,Payment Currency,Receiving Currency,Payment Format,Amount Received
  q5_projection_03:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q5_projection_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_raw_data
      OUTPUT_QUEUES: q5_projected_data
      NODE_PREFIX: q5_projection
      ID: '3'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_projection_03.txt
      CAMPOS: Timestamp,Payment Currency,Receiving Currency,Payment Format,Amount Received
  q5_projection_04:
    build:
      context: ./src
      dockerfile: workers/projection/Dockerfile
    container_name: q5_projection_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_raw_data
      OUTPUT_QUEUES: q5_projected_data
      NODE_PREFIX: q5_projection
      ID: '4'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_projection_04.txt
      CAMPOS: Timestamp,Payment Currency,Receiving Currency,Payment Format,Amount Received
  q5_filter_period_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q5_filter_period_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_projected_data
      OUTPUT_QUEUES: q5_period_to_format
      NODE_PREFIX: q5_filter_period
      ID: '1'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_filter_period_01.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01, 2022/09/05
      FILTER_OPERATOR: between
  q5_filter_period_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q5_filter_period_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_projected_data
      OUTPUT_QUEUES: q5_period_to_format
      NODE_PREFIX: q5_filter_period
      ID: '2'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_filter_period_02.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01, 2022/09/05
      FILTER_OPERATOR: between
  q5_filter_period_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q5_filter_period_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_projected_data
      OUTPUT_QUEUES: q5_period_to_format
      NODE_PREFIX: q5_filter_period
      ID: '3'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_filter_period_03.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01, 2022/09/05
      FILTER_OPERATOR: between
  q5_filter_period_04:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q5_filter_period_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_projected_data
      OUTPUT_QUEUES: q5_period_to_format
      NODE_PREFIX: q5_filter_period
      ID: '4'
      TOTAL_WORKERS: '4'
      LOG_FILE: /app/logs/q5_filter_period_04.txt
      FILTER_FIELD: Timestamp
      FILTER_VALUE: 2022/09/01, 2022/09/05
      FILTER_OPERATOR: between
  q5_filter_format_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q5_filter_format_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_period_to_format
      OUTPUT_QUEUES: q5_format_to_convert
      NODE_PREFIX: q5_filter_format
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q5_filter_format_01.txt
      FILTER_FIELD: Payment Format
      FILTER_VALUE: Wire, ACH
      FILTER_OPERATOR: in
  q5_filter_format_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: q5_filter_format_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_period_to_format
      OUTPUT_QUEUES: q5_format_to_convert
      NODE_PREFIX: q5_filter_format
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q5_filter_format_02.txt
      FILTER_FIELD: Payment Format
      FILTER_VALUE: Wire, ACH
      FILTER_OPERATOR: in
  q5_converter_01:
    build:
      context: ./src
      dockerfile: workers/converter/Dockerfile
    container_name: q5_converter_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_format_to_convert
      OUTPUT_QUEUES: q5_filtered
      NODE_PREFIX: q5_converter
      ID: '1'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q5_converter_01.txt
      START_DATE: '2022-09-01'
      END_DATE: '2022-09-05'
  q5_converter_02:
    build:
      context: ./src
      dockerfile: workers/converter/Dockerfile
    container_name: q5_converter_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_format_to_convert
      OUTPUT_QUEUES: q5_filtered
      NODE_PREFIX: q5_converter
      ID: '2'
      TOTAL_WORKERS: '2'
      LOG_FILE: /app/logs/q5_converter_02.txt
      START_DATE: '2022-09-01'
      END_DATE: '2022-09-05'
  q5_counter_01:
    build:
      context: ./src
      dockerfile: workers/counter/Dockerfile
    container_name: q5_counter_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: q5_filtered
      OUTPUT_QUEUES: q5_results
      NODE_PREFIX: q5_counter
      ID: '1'
      TOTAL_WORKERS: '1'
      LOG_FILE: /app/logs/q5_counter_01.txt
