services:
  gateway:
    build:
      context: ./src
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
    - "8080:8080"
    - "5678:5678"
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUE=raw_data
    - INPUT_QUEUE=filtered_data
    - HTTP_HOST=0.0.0.0
    - HTTP_PORT=8080

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - "5672:5672"
    - "15672:15672"

  filter_usd_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: filter_usd_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=raw_data
    - OUTPUT_QUEUE=usd_to_minor_50
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=filter_usd
    - ID=1
    - TOTAL_WORKERS=5
    - FILTER_FIELD=Payment Currency
    - FILTER_VALUE=US Dollar
    - FILTER_OPERATOR=eq
  filter_usd_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: filter_usd_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=raw_data
    - OUTPUT_QUEUE=usd_to_minor_50
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=filter_usd
    - ID=2
    - TOTAL_WORKERS=5
    - FILTER_FIELD=Payment Currency
    - FILTER_VALUE=US Dollar
    - FILTER_OPERATOR=eq
  filter_usd_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: filter_usd_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=raw_data
    - OUTPUT_QUEUE=usd_to_minor_50
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=filter_usd
    - ID=3
    - TOTAL_WORKERS=5
    - FILTER_FIELD=Payment Currency
    - FILTER_VALUE=US Dollar
    - FILTER_OPERATOR=eq
  filter_usd_04:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: filter_usd_04
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=raw_data
    - OUTPUT_QUEUE=usd_to_minor_50
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=filter_usd
    - ID=4
    - TOTAL_WORKERS=5
    - FILTER_FIELD=Payment Currency
    - FILTER_VALUE=US Dollar
    - FILTER_OPERATOR=eq
  filter_usd_05:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: filter_usd_05
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=raw_data
    - OUTPUT_QUEUE=usd_to_minor_50
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=filter_usd
    - ID=5
    - TOTAL_WORKERS=5
    - FILTER_FIELD=Payment Currency
    - FILTER_VALUE=US Dollar
    - FILTER_OPERATOR=eq
  minor_than_50_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: minor_than_50_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=usd_to_minor_50
    - OUTPUT_QUEUE=filtered_data
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=minor_than_50
    - ID=1
    - TOTAL_WORKERS=3
    - FILTER_FIELD=Amount Paid
    - FILTER_VALUE=50
    - FILTER_OPERATOR=lt
  minor_than_50_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: minor_than_50_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=usd_to_minor_50
    - OUTPUT_QUEUE=filtered_data
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=minor_than_50
    - ID=2
    - TOTAL_WORKERS=3
    - FILTER_FIELD=Amount Paid
    - FILTER_VALUE=50
    - FILTER_OPERATOR=lt
  minor_than_50_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: minor_than_50_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=usd_to_minor_50
    - OUTPUT_QUEUE=filtered_data
    - PYTHONUNBUFFERED=1
    - NODE_PREFIX=minor_than_50
    - ID=3
    - TOTAL_WORKERS=3
    - FILTER_FIELD=Amount Paid
    - FILTER_VALUE=50
    - FILTER_OPERATOR=lt
