include make/config.mk
include make/datasets.mk
include make/helpers.mk
include make/utils.mk
include make/run.mk
include make/tests.mk

.DEFAULT_GOAL := help

.PHONY: help

help:
	@echo ""
	@echo "  Uso: make <target> [argumentos...]"
	@echo ""
	@echo "  EJECUCION"
	@echo "  ─────────────────────────────────────────────────────────────────────────"
	@echo "  build                                  Buildea imagenes sin levantar"
	@echo "  start                                  Levanta el sistema (detached, sin rebuild)"
	@echo "  rebuild                                Rebuild + start (equivale al viejo start)"
	@echo "  down                                   Detiene el sistema"
	@echo "  cliente [tx] [acc] [sol]               Corre un cliente y compara con soluciones"
	@echo "  log <servicio>                         Muestra logs de un servicio"
	@echo ""
	@echo "  UTILIDADES"
	@echo "  ─────────────────────────────────────────────────────────────────────────"
	@echo "  workers-lista                           Lista workers activos y replicas"
	@echo "  workers-set <worker> <N>                Cambia replicas de un worker"
	@echo "  generar <queries>                       Genera docker-compose"
	@echo "  generar-sample <dataset> [%]            Genera sample de un dataset"
	@echo "  solucionar <tx> <acc> <dir>             Genera soluciones de referencia"
	@echo "  venv                                    Crea entorno virtual .venv"
	@echo "  install                                 Instala dependencias en .venv"
	@echo "  clean                                   Limpia caches, temporales, puertos e imágenes"
	@echo "  docker-clean                            Limpia imágenes dangling y build cache"
	@echo ""
	@echo "  TESTS UNITARIOS"
	@echo "  ─────────────────────────────────────────────────────────────────────────"
	@echo "  test-unit                               Todos los tests locales (sin containers)"
	@echo ""
	@echo "  CRASH HOOKS (determinísticos, un crash inyectado por instancia)"
	@echo "  ─────────────────────────────────────────────────────────────────────────"
	@echo "  Para activar un hook al levantar:"
	@echo "    <INSTANCIA>_CRASH=<HOOK> make start"
	@echo ""
	@echo "  Hooks disponibles:"
	@echo "    CRASH_BEFORE_DATA_ACK                 Despues de procesar dato, antes del ack"
	@echo "    CRASH_AFTER_PERSIST                   Despues de persistir, antes del ack"
	@echo "    CRASH_PRE_BARRERA                     Al recibir EOF, antes de iniciar barrera"
	@echo "    CRASH_BEFORE_FINISHED_CONFIRMATION    Antes de confirmar al originador"
	@echo "    CRASH_AFTER_FLUSH                     Despues del flush al completar cliente"
	@echo "    CRASH_BEFORE_EOF_FORWARD              Antes de reenviar EOF downstream"
	@echo ""
	@echo "  Ejemplo:"
	@echo "    Q5_COUNTER_01_CRASH=CRASH_PRE_BARRERA make start"
	@echo ""
	@echo "  Tests automatizados de crash:"
	@echo "  test-crash-worker-pre-confirm [cli] [tx] [acc] [sol] [TARGET]"
	@echo "  test-crash-worker-pre-barrera [cli] [tx] [acc] [sol] [TARGET]"
	@echo "  test-crash-worker-post-flush [etapa] [cli] [tx] [acc] [sol]"
	@echo "  test-crash-agregador-pending-acks [cli]"
	@echo "  test-crash-gateway [cli]                Prueba los hooks del gateway"
	@echo "  test-crash-watchdog [cli]               Prueba los hooks del watchdog"
	@echo "  test-crash-pipeline                     Todos los hooks x etapas x 1,2 clientes"
	@echo ""
	@echo "  CAOS (kill externo con el sistema andando)"
	@echo "  ─────────────────────────────────────────────────────────────────────────"
	@echo "  tirar-nodos [seg] [todos|etapa [p]]     Chaos monkey manual"
	@echo "  test-caos-total [cli] [espera] [intervalo]"
	@echo "                                          Mata todos los workers de golpe"
	@echo "  test-caos-aleatorio [seg] [cli]         Chaos monkey continuo"
	@echo "  test-caos-secuencial [seg] [cli]        Idem pero clientes secuenciales"
	@echo "  test-caos-etapa <prefijo> [cli]         Mata una etapa en loop"
	@echo "  test-caos-gateway [cli]                 Mata gateway en operacion"
	@echo "  test-caos-gateway-resultados            Mata gateway entregando resultados"
	@echo "  test-caos-cliente [cli]                 Mata un cliente a mitad de envio"
	@echo ""
	@echo "  SUITES"
	@echo "  ─────────────────────────────────────────────────────────────────────────"
	@echo "  iterar [N] [tx] [acc] [sol]             N clientes secuenciales (default 5)"
	@echo "  iterar-multi [iter] [cli] [tx] [acc] [sol]"
	@echo "                                          Rondas de clientes en paralelo (default 1x2)"
	@echo "  test-todos                              Suite completa (unit + crash + caos)"
	@echo "  test-todos-multi [N]                    Suite multicliente (default 3)"
	@echo "  test-stress-crash [iter]                Stress loop de crash hooks"
	@echo "  test-stress-caos [iter] [cli] [espera] [intervalo]"
	@echo "                                          Stress loop de caos"
	@echo ""
	@echo "  Defaults: tx=$(TEST_TX)  acc=$(TEST_ACC)  sol=$(TEST_SOL)"
	@echo ""

%:
	@:
