services:
  gateway:
    build:
      context: ./src
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5678:5678"
    volumes:
      - ./logs:/app/logs
    environment:
      PYTHONUNBUFFERED: '1'
      LOG_LEVEL: INFO
      LOG_FILE: /app/logs/gateway.txt
      SERVER_HOST: gateway
      SERVER_PORT: '5678'
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      OUTPUTS_QUEUE: ""
      INPUTS_QUEUE: ""
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: '8080'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_LOG_LEVELS: error
      RABBITMQ_DEFAULT_USER: distributed
      RABBITMQ_DEFAULT_PASS: distributed
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
      - "5672:5672"
      - "15672:15672"

  shared_filter_usd_01:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: shared_filter_usd_01
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    environment:
      PYTHONUNBUFFERED: '1'
      LOG_LEVEL: INFO
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: raw_data
      OUTPUT_QUEUES: '["q1_pre_projection", "q2_pre_projection", "q3_usd_filtered", "q4_pre_projection"]'
      NODE_PREFIX: shared_filter_usd
      ID: '1'
      TOTAL_WORKERS: '3'
      PREFETCH_COUNT: '10'
      HEARTBEAT_INTERVAL_SECONDS: '5'
      LOG_FILE: /app/logs/shared_filter_usd_01.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq

  shared_filter_usd_02:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: shared_filter_usd_02
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    environment:
      PYTHONUNBUFFERED: '1'
      LOG_LEVEL: INFO
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: raw_data
      OUTPUT_QUEUES: '["q1_pre_projection", "q2_pre_projection", "q3_usd_filtered", "q4_pre_projection"]'
      NODE_PREFIX: shared_filter_usd
      ID: '2'
      TOTAL_WORKERS: '3'
      PREFETCH_COUNT: '10'
      HEARTBEAT_INTERVAL_SECONDS: '5'
      LOG_FILE: /app/logs/shared_filter_usd_02.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq

  shared_filter_usd_03:
    build:
      context: ./src
      dockerfile: workers/filter/Dockerfile
    container_name: shared_filter_usd_03
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    environment:
      PYTHONUNBUFFERED: '1'
      LOG_LEVEL: INFO
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      INPUT_QUEUES: raw_data
      OUTPUT_QUEUES: '["q1_pre_projection", "q2_pre_projection", "q3_usd_filtered", "q4_pre_projection"]'
      NODE_PREFIX: shared_filter_usd
      ID: '3'
      TOTAL_WORKERS: '3'
      PREFETCH_COUNT: '10'
      HEARTBEAT_INTERVAL_SECONDS: '5'
      LOG_FILE: /app/logs/shared_filter_usd_03.txt
      FILTER_FIELD: Payment Currency
      FILTER_VALUE: US Dollar
      FILTER_OPERATOR: eq

  watchdog:
    build:
      context: ./src
      dockerfile: watchdog/Dockerfile
    container_name: watchdog
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
      - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      WATCHDOG_STAGES: ''
      HEARTBEAT_INTERVAL_SECONDS: '5'
      MISSED_HEARTBEATS_THRESHOLD: '3'
      CHECK_INTERVAL_SECONDS: '5'
      CAIDAS_QUEUE: caidas
      LOG_LEVEL: INFO
      LOG_FILE: /app/logs/watchdog.txt

  actuador:
    build:
      context: ./src
      dockerfile: watchdog/DockerfileActuador
    container_name: actuador
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs
    environment:
      MOM_HOST: rabbitmq
      MOM_PORT: '5672'
      MOM_USER: distributed
      MOM_PASSWORD: distributed
      MOM_VHOST: /
      CAIDAS_QUEUE: caidas
      LOG_LEVEL: INFO
      LOG_FILE: /app/logs/actuador.txt