from common.constantes_protocolo import COL_BANCO_ORIGEN, COL_CUENTA, COL_MONTO_PAGADO
from base.constantes import (
    CLAVE_BARRERA_COMPLETADA, CLAVE_EOF_MENSAJE,
    CLAVE_EOF_MENSAJE_HEX, CLAVE_IDS_PROCESADOS,
)

PREFIJO_BANK_SHARD = "bank_shard"

COL_ID_BANCO = "Bank ID"
COL_NOMBRE_BANCO = "Bank Name"
COL_MONTO_RECIBIDO = "Amount Received"

ESQUEMA_SALIDA = [COL_BANCO_ORIGEN, COL_CUENTA, COL_NOMBRE_BANCO, COL_MONTO_PAGADO]

NOMBRE_BANCO_DESCONOCIDO = "Desconocido"

CLAVE_NOMBRE_BANCO = "bank_name"
CLAVE_MONTO_MAXIMO = "max_amount"
CLAVE_CUENTAS = "accounts"

CLAVE_TX_EOF_COUNT = "tx_eof_count"
CLAVE_BANK_EOF_COUNT = "bank_eof_count"
CLAVE_FLUSH_INICIADO = "flush_iniciado"
CLAVE_BANCOS = "bancos"

COLA_TRANSACCIONES = "transactions"
COLA_BANCOS = "banks"

ENV_TOTAL_TX_UPSTREAM = "TOTAL_TX_UPSTREAM"
ENV_TOTAL_BANK_UPSTREAM = "TOTAL_BANK_UPSTREAM"

INTERVALO_PERSISTENCIA = 500
